name: Tripory
options:
  bundleIdPrefix: com.tomokichi
  deploymentTarget:
    iOS: "26.0"
  createIntermediateGroups: true
  developmentLanguage: ja
targets:
  Tripory:
    type: application
    platform: iOS
    sources:
      - Tripory
    settings:
      base:
        DEVELOPMENT_TEAM: 7GU925RQ99
        PRODUCT_BUNDLE_IDENTIFIER: com.tomokichi.Journeys
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_CFBundleDisplayName: Tripory
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.0"
        LOCALIZATION_PREFERS_STRING_CATALOGS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        ASSETCATALOG_COMPILER_APPICON_NAME: ""

  TriporyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TriporyTests
    dependencies:
      - target: Tripory
    settings:
      base:
        DEVELOPMENT_TEAM: 7GU925RQ99
        PRODUCT_BUNDLE_IDENTIFIER: com.tomokichi.JourneysTests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.0"

schemes:
  Tripory:
    build:
      targets:
        Tripory: all
        TriporyTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TriporyTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
